#!/bin/bash

# This script will download and setup slack in a container.

# MIT License
#
# Copyright (c) 2016 Stefan Berggren
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

USE_X=True
CONTAINER=slack
. $(dirname $0)/setup-container

install_packages libgtk2.0-0 libudev0 libnotify4 libxtst6 libnss3 python \
	gvfs-bin xdg-utils apt-transport-https libxss1

# Get latest release
download_file \
	https://downloads.slack-edge.com/linux_releases/slack-desktop-2.0.6-amd64.deb \
	slack-desktop-2.0.6-amd64.deb \
	8c91ef57f4c4b2fec9e5d3d3ad6f54b7b15da269c041a0e1a37c76b133097528

install_deb /home/$CONTAINER/slack-desktop-2.0.6-amd64.deb slack-desktop

setup_x_socket
run_cmd_user slack

lxc-stop -n $CONTAINER -t 10
