#!/bin/bash

# MIT License
#
# Copyright (c) 2016 Stefan Berggren
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

USE_X=True
CONTAINER=servo-nightly
BASED_ON="-d ubuntu -r trusty -a amd64"
. $(dirname $0)/setup-container

install_packages bzip2 libgtk-3-0 libasound2 libxtst6 libxt6 libegl1-mesa libgl1-mesa-glx libxmu6

# Get latest release
download_file \
	https://download.servo.org/nightly/linux/servo-latest.tar.gz \
	servo-latest.tar.gz

if ! has_file home/$CONTAINER/servo; then
	run_cmd_user tar xfv servo-latest.tar.gz
fi

run_cmd_bash "echo -e '#!/bin/bash\ncd \$(dirname \$0)\n./runservo.sh' > home/$CONTAINER/servo/runservo-wr.sh"
run_cmd chmod +x home/$CONTAINER/servo/runservo-wr.sh

setup_x_socket
setup_sound
setup_video
run_cmd_user ./servo/runservo-wr.sh

lxc-stop -n $CONTAINER -t 10
