#!/bin/bash

# This script will download and setup yakyak in a container.

# MIT License
#
# Copyright (c) 2016 Stefan Berggren
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.


USE_X=True
CONTAINER=yakyak
. $(dirname $0)/setup-container

install_packages unzip libgtk2.0-0 libxss1 libgconf-2-4 libnss3 libasound2 libudev0 libxtst6
download_file https://github.com/yakyak/yakyak/releases/download/v1.3.0/yakyak-linux-x64.zip yakyak-linux-x64.zip

if ! has_file home/yakyak/linux-x64; then
	set -x
	run_cmd_user unzip yakyak-linux-x64.zip
fi

run_cmd_user ./linux-x64/yakyak

lxc-stop -n $CONTAINER -t 10
